version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.sang.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.144.233.86:9300'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '9300:9300'
      - '2224:22'
    volumes:
      - '/opt/to/gitlab/config:/etc/gitlab'
      - '/opt/to/gitlab/logs:/var/log/gitlab'
      - '/opt/to/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
