version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.sang.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.144.233.86:9300'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.office365.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "xiaoyihou@outlook.com"
        gitlab_rails['smtp_password'] = "*******"
        gitlab_rails['smtp_domain'] = "smtp-mail.outlook.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['gitlab_email_from'] = 'xiaoyihou@outlook.com'
    ports:
      - '9300:9300'
      - '2224:22'
    volumes:
      - '/opt/to/gitlab/config:/etc/gitlab'
      - '/opt/to/gitlab/logs:/var/log/gitlab'
      - '/opt/to/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
