version: "3.7"

services:
  influx:
    image: influxdb:1.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
      - influxconf:/etc/influxdb
  chronograf:
    image: chronograf:1.7
    ports:
      - "8888:8888"
    volumes:
      - chronograf:/var/lib/chronograf
volumes:
  influxdb:
  influxconf:
  chronograf:
