version: "3.7"

services:
  influx:
    image: influxdb:1.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
      - influxconf:/etc/influxdb
  chronograf:
    image: chronograf:1.7
    ports:
      - "8888:8888"
    volumes:
      - chronograf:/var/lib/chronograf
  grafana:
    image: grafana:8.3.3
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
volumes:
  influxdb:
  influxconf:
  chronograf:
  grafana:
