version: "3.7"

services:
  mysql:
    image: mysql:latest
#    restart: always
    ports:
      - "13306:3306"
    volumes:
      - /opt/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: w7s6bi
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /docker/host/dir:/data
  minio:
    container_name: lumen-minio
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_DEFAULT_BUCKETS=my-first-bucket,my-second-bucket


#  influx:
#    image: influxdb:1.7
#    ports:
#      - "8086:8086"
#    volumes:
#      - influxdb:/var/lib/influxdb
#      - influxconf:/etc/influxdb
#  chronograf:
#    image: chronograf:1.7
#    ports:
#      - "8888:8888"
#    volumes:
#      - chronograf:/var/lib/chronograf
#  grafana:
#    image: grafana:8.3.3
#    ports:
#      - "3000:3000"
#    volumes:
#      - grafana:/var/lib/grafana
#volumes:
#  influxdb:
#  influxconf:
#  chronograf:
#  grafana:
