version: "3.7"

services:
  mysql:
    container_name: lumen-mysql
    image: mysql:latest
#    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./to/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: w7s6bi
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
  redis:
    container_name: lumen-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./to/redis/data:/data
  minio:
    container_name: lumen-minio
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./to/minio/data:/data
      - ./to/minio/config:/root/.minio
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_DEFAULT_BUCKETS=my-first-bucket,my-second-bucket
      - TZ=Asia/Shanghai
  prometheus:
    container_name: lumen-prometheus
    image: bitnami/prometheus:2.37.0
    ports:
      - '9090:9090'
    volumes:
      - ./to/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./to/prometheus/data:/prometheus
  grafana: # dashboard ids : 4701 12900
    container_name: lumen-grafana
    image: grafana/grafana:9.0.4
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "3000:3000"
    volumes:
      - ./to/grafana/data:/var/lib/grafana
      - ./to/grafana/config/grafana.ini:/etc/grafana/grafana.ini

