### 添加或者更新job
PUT {{protocol}}{{domain}}/lumen/task/job
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "jobName": "demo2",
  "jobGroup": "demo2",
  "description": "",
  "beanClass": "com.sang.system.job.BadJob",
  "shouldRecover": false,
  "jobDataMap": {
    "test" : 1,
    "test2" : 2,
    "test3" : "3"
  }
}


### 删除job
DELETE {{protocol}}{{domain}}/lumen/task/job
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "jobName": "demo2",
  "jobGroup": "demo2"
}

###
PUT {{protocol}}{{domain}}/lumen/task/job/run
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "jobName": "demo1",
  "jobGroup": "demo"
}


### 添加触发器
POST {{protocol}}{{domain}}/lumen/task/triggers
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "jobName": "demo1",
  "jobGroup": "demo",
  "triggerVos": [
    {
      "triggerName": "demo1",
      "triggerGroup": "demo",
      "triggerDescription": "",
      "cronExpression": "0/3 * * * * ?"
    }
  ]
}

### 删除对应的触发器
DELETE {{protocol}}{{domain}}/lumen/task/triggers
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {
      "triggerName": "demo1",
      "triggerGroup": "demo"
    }
]

### 更新job对应的触发器
PUT {{protocol}}{{domain}}/lumen/task/triggers
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "jobName": "demo1",
  "jobGroup": "demo",
  "triggerVos": [
    {
      "triggerName": "demo1",
      "triggerGroup": "demo",
      "triggerDescription": "",
      "cronExpression": "0 20 * * * ?"
    }
  ]
}


### 获取所有job group
GET {{protocol}}{{domain}}/lumen/task/job/groups
Authorization: Bearer {{token}}

### 按照jobgroup 获取job列表，group为空获取全部
GET {{protocol}}{{domain}}/lumen/task/getJobList
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "jobName": "demo1",
  "jobGroup": "demo"
}


### 获取job下的所有trigger
POST {{protocol}}{{domain}}/lumen/task/job/triggers
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "jobName": "demo1",
  "jobGroup": "demo"
}

### 获取所有正在运行的job
GET {{protocol}}{{domain}}/lumen/task/running/job
Authorization: Bearer {{token}}

### 暂停一个job直到调用恢复为止都不会被执行
PUT {{protocol}}{{domain}}/lumen/task/job/pause
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "jobName": "demo1",
  "jobGroup": "demo"
}

### 恢复一个被暂停的job使其可以继续执行
PUT {{protocol}}{{domain}}/lumen/task/job/resume
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "jobName": "demo1",
  "jobGroup": "demo"
}


### 添加job监听器
PUT {{protocol}}{{domain}}/lumen/task/job/listener
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "jobName": "demo1",
  "jobGroup": "demo",
  "jobListener": "com.sang.system.job.listener.DemoJobListener"
}

### 删除job监听器
DELETE {{protocol}}{{domain}}/lumen/task/job/listener
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "jobListener": "demoListener1"
}