### 根据当前用户返回路由列表
GET http://localhost:8080/lumen/router/routerTree
Authorization: Bearer {{token}}

### 保存
POST http://localhost:8080/lumen/router/router
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "菜单管理8",
  "path": "/router/menu8",
  "redirect": "/",
  "component": "/menage/router8",
  "mate": {"title": "菜单管理8","icon":"Sunset"},
  "description": "",
  "hidden": false,
  "alwaysShow": true,
  "orderBy": 2,
  "parentId" : {
    "id": 435576735858933760
  },
  "roles": [
    {
      "id": 435165139135348736
    }
  ]
}

### 通过id更新
PUT http://localhost:8080/lumen/router/router
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 435587805562519552,
  "name": "菜单管理2",
  "path": "/router/menu2",
  "redirect": "/",
  "component": "/menage/router1",
  "mate": "{\"id\": 0}",
  "description": "",
  "hidden": false,
  "alwaysShow": true,
  "orderBy": 2,
  "parentId" : {
    "id": 435576735858933760
  },
  "roles": [
    {
      "id": 435165139135348736
    }
  ]
}

### 批量保存
POST http://localhost:8080/lumen/router/routers
Content-Type: application/json
Authorization: Bearer {{token}}

[
  {
    "name": "菜单管理3",
    "path": "/router/menu3",
    "redirect": "/",
    "component": "/menage/router3",
    "mate": "{\"id\": 0}",
    "description": "",
    "hidden": false,
    "alwaysShow": true,
    "orderBy": 2,
    "parentId" : {
      "id": 435576735858933760
    },
    "roles": [
      {
        "id": 435165139135348736
      }
    ]
  },
  {
    "name": "菜单管理4",
    "path": "/router/menu4",
    "redirect": "/",
    "component": "/menage/router4",
    "mate": "{\"id\": 0}",
    "description": "",
    "hidden": false,
    "alwaysShow": true,
    "orderBy": 2,
    "parentId" : {
      "id": 435576735858933760
    },
    "roles": [
      {
        "id": 435165139135348736
      }
    ]
  }
]

### 通过id删除
DELETE http://localhost:8080/lumen/router/router
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 435588650966433792
}

### 批量删除
DELETE http://localhost:8080/lumen/router/routers
Content-Type: application/json
Authorization: Bearer {{token}}

[
  {
    "id": 435588650966433792
  },
  {
    "id": 435588650970628096
  },
  {
    "id": 457616453261799424
  },
  {
    "id": 457616504210010112
  },
  {
    "id": 457616548606717952
  },
  {
    "id": 457616854480531456
  }
]

### 根据当前用户返回路由列表
GET http://localhost:8080/lumen/router/routers
Authorization: Bearer {{token}}
