kubectl create secret docker-registry secret-docker-harbor \
--docker-email=xiaoyihou@outlook.com \
--docker-username=sang \
--docker-password=Hkbat233. \
--docker-server=10.144.233.86:8082
-n sang-lumen
