
datasource:
  db:
    username: root
    password: w7s6bi
    url: jdbc:mysql://129.211.190.27:3307/jins_master?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
ebean:
  test:
    platform: h2 # h2, postgres, mysql, mariadb, oracle, sqlserver, hana, clickhouse, sqlite
    ddlMode: dropCreate # none | dropCreate | migration
    dbName: my_app
logging:
  level:
    io:
      ebean:
        SQL: DEBUG
        TXN: DEBUG
#spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#    redis:
#      database: 0
#      port: 6379
#      host: 127.0.0.1
#      #    password:
#      timeout: 2000
#      jedis:
#        pool:
#          max-active: 50
#          max-idle: 50
#          min-idle: 0
#          max-wait: 2000
