ebean:
  ## run migrations when the EbeanServer starts
  migration:
    run: true
  db:
    ddl:
      generate: true
      run: true
logging:
  level:
    io:
      ebean:
        SQL: DEBUG
        TXN: DEBUG
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
  expire: 36000
  refresh-expiry: 72000
#spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#    redis:
#      database: 0
#      port: 6379
#      host: 127.0.0.1
#      #    password:
#      timeout: 2000
#      jedis:
#        pool:
#          max-active: 50
#          max-idle: 50
#          min-idle: 0
#          max-wait: 2000
spring:
  profiles:
    active: gs
