spring:
  redis:
    database: 0
    port: 6380
    host: 10.144.233.86
#    password: c5fSVo
    timeout: 2000
    jedis:
      pool:
        max-active: 50
        max-idle: 50
        min-idle: 0
        max-wait: 2000
datasource:
  db:
    username: root
    password: w7s6bi
    url: jdbc:mysql://10.144.233.86:3307/lumen_server?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
logging:
  level:
    io:
      ebean:
        SQL: DEBUG
        TXN: DEBUG
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
  expire: 3600
  refresh-expiry: 72000
minio:
  credentials: classpath:credentials.json
  bucket:
    master: my-first-bucket
    second: my-second-bucket
#management:
#  metrics:
#    export:
#      influx:
#        auto-create-db: true # Whether to create the InfluxDB database if it does not exist before attempting to publish metrics to it. InfluxDB v1 only. (Default: true)
#        batch-size: 10000 # Number of measurements per request to use for this backend. If more measurements are found, then multiple requests will be made. (Default: 10000)
#        compressed: true # Whether to enable GZIP compression of metrics batches published to InfluxDB. (Default: true)
#        connect-timeout: 1s # Connection timeout for requests to this backend. (Default: 1s)
#        consistency: one # Write consistency for each point. (Default: one)
#        db: mydb # Database to send metrics to. InfluxDB v1 only. (Default: mydb)
#        enabled: true # Whether exporting of metrics to this backend is enabled. (Default: true)
#        user-name: admin # Login user of the InfluxDB server. InfluxDB v1 only.
#        password: admin # Login password of the InfluxDB server. InfluxDB v1 only.
#        read-timeout: 10s # Read timeout for requests to this backend. (Default: 10s)
#        retention-policy: my_rp # Retention policy to use (InfluxDB writes to the DEFAULT retention policy if one is not specified). InfluxDB v1 only.
#        step: 1m # Step size (i.e. reporting frequency) to use. (Default: 1m)
#        uri: http://localhost:8086 # URI of the InfluxDB server. (Default: http://localhost:8086)
