###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "hxy",
  "password": "123456"
}

> {% client.global.set("token", response.body.token); %}

###
PUT http://localhost:8080/lumen/storage/upload
Authorization: Bearer {{token}}

